name: Build image

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15 # Using macOS as https://github.com/actions/virtual-environments/issues/183
    steps:
      - uses: actions/checkout@v2
      - name: Download base image
        run: |
          mkdir output-virtualbox-iso
          wget --progress=dot:giga https://clovervm.ams3.digitaloceanspaces.com/base-focal.ova -O output-virtualbox-iso/clover-devel.ova
      - name: Build
        run: ./build.sh
