name: Build image

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          wget https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key
          add - && sudo sh -c "echo deb https://download.virtualbox.org/virtualbox/debian
          bionic contrib >> /etc/apt/sources.list" && sudo apt-get update && sudo apt-get
          install build-essential gcc make linux-headers-$(uname -r) virtualbox-6.0 && sudo
          usermod -aG vboxusers $(whoami)
          mkdir output-virtualbox-iso && pushd output-virtualbox-iso && wget --progress=dot:giga https://github.com/sfalexrog/clever_vm/releases/download/v0.1_base_vm/clover-devel.ova && popd
          sudo apt install -y xvfb
      - name: Build
        run: xvfb-run ./build.sh